export default function PrivacyPage() {
	return (
		<article className="prose mx-auto container px-4 py-8">
			<h1>Privacy Policy</h1>
			<p>
				This Privacy Policy describes Our policies and procedures on the collection, use and disclosure
				of Your information when You use the Service and tells You about Your privacy rights and how the
				law protects You.
			</p>
			<p>
				We use Your Personal data to provide and improve the Service. By using the Service, You agree to
				the collection and use of information in accordance with this Privacy Policy. This Privacy
				Policy has been created with the help of the{' '}
				<a
					href="https://www.privacypolicies.com/blog/privacy-policy-template/"
					target="_blank"
					rel="noopener noreferrer"
				>
					Privacy Policy Template
				</a>.
			</p>
			<h2>Interpretation and Definitions</h2>
			<h3>Interpretation</h3>
			<p>
				The words of which the initial letter is capitalized have meanings defined under the following
				conditions. The following definitions shall have the same meaning regardless of whether they
				appear in singular or in plural.
			</p>
			<h3>Definitions</h3>
			<p>For the purposes of this Privacy Policy:</p>
			<ul>
				<li>
					<p>
						<strong>Account</strong> means a unique account created for You to access our Service or parts
						of our Service.
					</p>
				</li>
				<li>
					<p>
						<strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement)
						refers to You, Nowhereville.
					</p>
				</li>
				<li>
					<p>
						<strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any
						other device by a website, containing the details of Your browsing history on that website among
						its many uses.
					</p>
				</li>
				<li>
					<p><strong>Country</strong> refers to: Alaska, United States</p>
				</li>
				<li>
					<p>
						<strong>Device</strong> means any device that can access the Service such as a computer, a cellphone
						or a digital tablet.
					</p>
				</li>
				<li>
					<p>
						<strong>Personal Data</strong> is any information that relates to an identified or identifiable
						individual.
					</p>
				</li>
				<li>
					<p><strong>Service</strong> refers to the Website.</p>
				</li>
				<li>
					<p>
						<strong>Service Provider</strong> means any natural or legal person who processes the data on
						behalf of the Company. It refers to third-party companies or individuals employed by the Company
						to facilitate the Service, to provide the Service on behalf of the Company, to perform services
						related to the Service or to assist the Company in analyzing how the Service is used.
					</p>
				</li>
				<li>
					<p>
						<strong>Usage Data</strong> refers to data collected automatically, either generated by the use
						of the Service or from the Service infrastructure itself (for example, the duration of a page
						visit).
					</p>
				</li>
				<li>
					<p>
						<strong>Website</strong> refers to RBay, accessible from
						<a href="https://redis-rbay.com" rel="external nofollow noopener" target="_blank">
							https://redis-rbay.com
						</a>
					</p>
				</li>
				<li>
					<p>
						<strong>You</strong> means the individual accessing or using the Service, or the company, or
						other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
					</p>
				</li>
			</ul>
		</article>
	);
}
